
-- alert

Schema.voices.Add("Conscript", "CONTACT", "Contact!", "litenetwork/vo/conscript/hg_alert01.wav")
Schema.voices.Add("Conscript", "CONTACT2", "Contact!", "litenetwork/vo/conscript/hg_alert01_var02.wav")
Schema.voices.Add("Conscript", "CONTACT3", "Contact!", "litenetwork/vo/conscript/hg_alert02.wav")
Schema.voices.Add("Conscript", "CONTACT4", "Contact!", "litenetwork/vo/conscript/hg_alert03.wav")
Schema.voices.Add("Conscript", "CONTACT5", "Contact!", "litenetwork/vo/conscript/hg_alert03_var02.wav")
Schema.voices.Add("Conscript", "CONTACT6", "Contact, we've got contact!", "litenetwork/vo/conscript/hg_alert04.wav")
Schema.voices.Add("Conscript", "CONTACT7", "Shit, contact!", "litenetwork/vo/conscript/hg_alert09_var01.wav")
Schema.voices.Add("Conscript", "CONTACT8", "Contact! Contact!", "litenetwork/vo/conscript/hg_alert16.wav")
Schema.voices.Add("Conscript", "CONTACT9", "Contact! Contact!", "litenetwork/vo/conscript/hg_alert16_var01.wav")
Schema.voices.Add("Conscript", "TARGET", "Target!", "litenetwork/vo/conscript/hg_alert05.wav")
Schema.voices.Add("Conscript", "TARGET2", "Target!", "litenetwork/vo/conscript/hg_alert05_var02.wav")
Schema.voices.Add("Conscript", "TARGET3", "Target!", "litenetwork/vo/conscript/hg_alert05_var03.wav")
Schema.voices.Add("Conscript", "TARGET4", "Target!", "litenetwork/vo/conscript/hg_alert05_var06.wav")
Schema.voices.Add("Conscript", "WE GOT CONTACT", "Squad, we got contact!", "litenetwork/vo/conscript/hg_alert06.wav")
Schema.voices.Add("Conscript", "WE GOT CONTACT2", "Squad, we got contact!", "litenetwork/vo/conscript/hg_alert06_var02.wav")
Schema.voices.Add("Conscript", "WE GOT CONTACT3", "We got contact!", "litenetwork/vo/conscript/hg_alert06_var03.wav")
Schema.voices.Add("Conscript", "HEY", "Hey!", "litenetwork/vo/conscript/hg_alert08.wav")
Schema.voices.Add("Conscript", "HEADS UP", "Heads up!", "litenetwork/vo/conscript/hg_alert11.wav")
Schema.voices.Add("Conscript", "HEADS UP2", "Heads up!", "litenetwork/vo/conscript/hg_alert11_var02.wav")
Schema.voices.Add("Conscript", "HEADS UP3", "Heads up! We got a hostile!", "litenetwork/vo/conscript/hg_alert12_var01.wav")
Schema.voices.Add("Conscript", "HEADS UP4", "Heads up! We got a hostile!", "litenetwork/vo/conscript/hg_alert12_var03.wav")
Schema.voices.Add("Conscript", "RIGHT THERE", "There! Right there!", "litenetwork/vo/conscript/hg_alert13.wav")
Schema.voices.Add("Conscript", "RIGHT THERE2", "There! Right there!", "litenetwork/vo/conscript/hg_alert13_var02.wav")
Schema.voices.Add("Conscript", "MOVEMENT", "Movement!", "litenetwork/vo/conscript/hg_alert14.wav")
Schema.voices.Add("Conscript", "MOVEMENT2", "Movement!", "litenetwork/vo/conscript/hg_alert14_var02.wav")
Schema.voices.Add("Conscript", "MOVEMENT3", "We got movement!", "litenetwork/vo/conscript/hg_alert15_var01.wav")
Schema.voices.Add("Conscript", "MOVE", "Move!", "litenetwork/vo/conscript/hg_alert18.wav")

-- answer

Schema.voices.Add("Conscript", "ROGER THAT", "Uh, roger that.", "litenetwork/vo/conscript/hg_answer01.wav")
Schema.voices.Add("Conscript", "YUP", "Yup.", "litenetwork/vo/conscript/hg_answer02.wav")
Schema.voices.Add("Conscript", "AFFIRMATIVE", "Affirmative.", "litenetwork/vo/conscript/hg_answer03.wav")
Schema.voices.Add("Conscript", "YEAH", "Yeah.", "litenetwork/vo/conscript/hg_answer04.wav")
Schema.voices.Add("Conscript", "ROGER", "Roger.", "litenetwork/vo/conscript/hg_answer05_var01.wav")
Schema.voices.Add("Conscript", "YEAH2", "Yeah, yeah.", "litenetwork/vo/conscript/hg_answer06_var02.wav")
Schema.voices.Add("Conscript", "AFFIRMATIVE2", "That is, uhh... affirmative.", "litenetwork/vo/conscript/hg_answer07.wav")
Schema.voices.Add("Conscript", "GOOD TO GO", "Good to go.", "litenetwork/vo/conscript/hg_answer08_var01.wav")
Schema.voices.Add("Conscript", "ROGER THAT2", "Roger that.", "litenetwork/vo/conscript/hg_answer09.wav")
Schema.voices.Add("Conscript", "AFFIRMATIVE3", "That's affirmative.", "litenetwork/vo/conscript/hg_answer10.wav")
Schema.voices.Add("Conscript", "UH HUH", "Uh huh.", "litenetwork/vo/conscript/hg_answer11_var02.wav")
Schema.voices.Add("Conscript", "COPY THAT", "Copy that.", "litenetwork/vo/conscript/hg_answer12.wav")
Schema.voices.Add("Conscript", "UNDERSTOOD", "Understood.", "litenetwork/vo/conscript/hg_answer13.wav")
Schema.voices.Add("Conscript", "I HEAR YOU", "I hear you.", "litenetwork/vo/conscript/hg_answer14.wav")
Schema.voices.Add("Conscript", "I HEAR YOU2", "I hear you.", "litenetwork/vo/conscript/hg_answer14_var02.wav")
Schema.voices.Add("Conscript", "I UNDERSTAND", "I understand, yeah.", "litenetwork/vo/conscript/hg_answer15.wav")
Schema.voices.Add("Conscript", "I UNDERSTAND2", "Yeah, I understand.", "litenetwork/vo/conscript/hg_answer15_var03.wav")
Schema.voices.Add("Conscript", "MHM", "Mhm.", "litenetwork/vo/conscript/hg_answer16.wav")
Schema.voices.Add("Conscript", "MHM2", "Mhm.", "litenetwork/vo/conscript/hg_answer16_subd01.wav")

-- charge

Schema.voices.Add("Conscript", "PUSH", "Push!", "litenetwork/vo/conscript/hg_charge01.wav")
Schema.voices.Add("Conscript", "PUSH2", "Push!", "litenetwork/vo/conscript/hg_charge01_var01.wav")
Schema.voices.Add("Conscript", "MOVE IN", "Move in!", "litenetwork/vo/conscript/hg_charge02.wav")
Schema.voices.Add("Conscript", "MOVE IN2", "Move in!", "litenetwork/vo/conscript/hg_charge02_subd01.wav")
Schema.voices.Add("Conscript", "MOVE IN3", "Move in!", "litenetwork/vo/conscript/hg_charge02_var01.wav")
Schema.voices.Add("Conscript", "MOVE IN4", "Move in!", "litenetwork/vo/conscript/hg_charge02_var02.wav")
Schema.voices.Add("Conscript", "MOVE IN5", "Move in!", "litenetwork/vo/conscript/hg_charge02_var03.wav")
Schema.voices.Add("Conscript", "GO", "Go!", "litenetwork/vo/conscript/hg_charge03.wav")
Schema.voices.Add("Conscript", "GO2", "Go!", "litenetwork/vo/conscript/hg_charge03_subd01.wav")
Schema.voices.Add("Conscript", "GO3", "Go!", "litenetwork/vo/conscript/hg_charge03_var01.wav")
Schema.voices.Add("Conscript", "GO4", "Go!", "litenetwork/vo/conscript/hg_charge03_var02.wav")
Schema.voices.Add("Conscript", "GO5", "Go!", "litenetwork/vo/conscript/hg_charge03_var03.wav")
Schema.voices.Add("Conscript", "PUSH3", "Push, push, push!", "litenetwork/vo/conscript/hg_charge05.wav")
Schema.voices.Add("Conscript", "PUSH4", "Go, go! Push, push, push!", "litenetwork/vo/conscript/hg_charge05_extrm01.wav")
Schema.voices.Add("Conscript", "PUSH5", "Push, push, push!", "litenetwork/vo/conscript/hg_charge05_var01.wav")
Schema.voices.Add("Conscript", "GO GO GO", "Go, go go!", "litenetwork/vo/conscript/hg_charge06.wav")
Schema.voices.Add("Conscript", "GO GO GO2", "Go, go, go!", "litenetwork/vo/conscript/hg_charge06_extrm01.wav")
Schema.voices.Add("Conscript", "GO GO GO3", "Go, go, go!", "litenetwork/vo/conscript/hg_charge06_var01.wav")
Schema.voices.Add("Conscript", "GET THEM", "Get them!'", "litenetwork/vo/conscript/hg_charge07.wav")
Schema.voices.Add("Conscript", "GET THEM2", "Get them!'", "litenetwork/vo/conscript/hg_charge07_extrm01.wav")
Schema.voices.Add("Conscript", "GET THEM3", "Get them!", "litenetwork/vo/conscript/hg_charge07_extrm02.wav")
Schema.voices.Add("Conscript", "GET THEM4", "Get them!'", "litenetwork/vo/conscript/hg_charge07_var01.wav")
Schema.voices.Add("Conscript", "GET THEM5", "Get them, now!'", "litenetwork/vo/conscript/hg_charge07_var02.wav")
Schema.voices.Add("Conscript", "GET THEM6", "Go, get them!'", "litenetwork/vo/conscript/hg_charge08.wav")
Schema.voices.Add("Conscript", "GET THEM7", "Go, get them!'", "litenetwork/vo/conscript/hg_charge08_var01.wav")
Schema.voices.Add("Conscript", "GET THEM8", "Go get them'", "litenetwork/vo/conscript/hg_charge08_var02.wav")
Schema.voices.Add("Conscript", "GET THEM9", "Go, get them!'", "litenetwork/vo/conscript/hg_charge08_var03.wav")
Schema.voices.Add("Conscript", "OK GO", "Ok, go!", "litenetwork/vo/conscript/hg_charge09.wav")
Schema.voices.Add("Conscript", "OK GO2", "Ok, go!", "litenetwork/vo/conscript/hg_charge09_subd01.wav")
Schema.voices.Add("Conscript", "OK GO3", "Ok, go!", "litenetwork/vo/conscript/hg_charge09_subd02.wav")
Schema.voices.Add("Conscript", "OK GO4", "Ok, go!", "litenetwork/vo/conscript/hg_charge09_var01.wav")
Schema.voices.Add("Conscript", "GO GO GO4", "Go, go, go!", "litenetwork/vo/conscript/hg_charge09_var02.wav")
Schema.voices.Add("Conscript", "OK GO5", "Ok, go, go!", "litenetwork/vo/conscript/hg_charge09_var03.wav")
Schema.voices.Add("Conscript", "PUT THEM DOWN", "Put them down!'", "litenetwork/vo/conscript/hg_charge10.wav")
Schema.voices.Add("Conscript", "PUT THEM DOWN2", "Put them down!", "litenetwork/vo/conscript/hg_charge10_var01.wav")
Schema.voices.Add("Conscript", "PUT THEM DOWN3", "Put them down!", "litenetwork/vo/conscript/hg_charge10_var02.wav")
Schema.voices.Add("Conscript", "PUT THEM DOWN4", "Put them down!", "litenetwork/vo/conscript/hg_charge10_var03.wav")
Schema.voices.Add("Conscript", "MOVING", "Moving!", "litenetwork/vo/conscript/hg_charge11.wav")
Schema.voices.Add("Conscript", "MOVING2", "Moving!", "litenetwork/vo/conscript/hg_charge11_var01.wav")
Schema.voices.Add("Conscript", "MOVING3", "Moving!", "litenetwork/vo/conscript/hg_charge11_var02.wav")
Schema.voices.Add("Conscript", "GOING IN", "Cover me, I'm going in!", "litenetwork/vo/conscript/hg_charge12.wav")
Schema.voices.Add("Conscript", "GOING IN2", "Going in, cover me!", "litenetwork/vo/conscript/hg_charge12_var01.wav")
Schema.voices.Add("Conscript", "GOING IN3", "Going in, cover me!", "litenetwork/vo/conscript/hg_charge12_var02.wav")
Schema.voices.Add("Conscript", "GOING IN4", "I'm going in!", "litenetwork/vo/conscript/hg_charge13.wav")
Schema.voices.Add("Conscript", "GOING IN5", "I'm going in!", "litenetwork/vo/conscript/hg_charge13_subd01.wav")
Schema.voices.Add("Conscript", "GOING IN6", "I'm going in!", "litenetwork/vo/conscript/hg_charge13_var01.wav")
Schema.voices.Add("Conscript", "GOING IN7", "Heads up, I'm going in!", "litenetwork/vo/conscript/hg_charge13_var02.wav")
Schema.voices.Add("Conscript", "GOING IN8", "Going in!", "litenetwork/vo/conscript/hg_charge14.wav")
Schema.voices.Add("Conscript", "GOING IN9", "Going in!", "litenetwork/vo/conscript/hg_charge14_var01.wav")
Schema.voices.Add("Conscript", "GOING IN10", "Going in!", "litenetwork/vo/conscript/hg_charge14_var02.wav")
Schema.voices.Add("Conscript", "TAKE THEM", "Take them!", "litenetwork/vo/conscript/hg_charge15.wav")
Schema.voices.Add("Conscript", "TAKE THEM2", "Take them!", "litenetwork/vo/conscript/hg_charge15_var01.wav")
Schema.voices.Add("Conscript", "TAKE THEM3", "Take them!", "litenetwork/vo/conscript/hg_charge15_var02.wav")
Schema.voices.Add("Conscript", "DROP THEM", "Drop them!", "litenetwork/vo/conscript/hg_charge16.wav")
Schema.voices.Add("Conscript", "DROP THEM2", "Drop them!", "litenetwork/vo/conscript/hg_charge16_var01.wav")
Schema.voices.Add("Conscript", "PUSH FORWARD", "Push forward!", "litenetwork/vo/conscript/hg_charge17.wav")
Schema.voices.Add("Conscript", "PUSH FORWARD2", "Push forward!", "litenetwork/vo/conscript/hg_charge17_var01.wav")
Schema.voices.Add("Conscript", "PUSH IN", "Push in!", "litenetwork/vo/conscript/hg_charge18.wav")
Schema.voices.Add("Conscript", "PUSH IN2", "Push in!", "litenetwork/vo/conscript/hg_charge18_var01.wav")

-- check

Schema.voices.Add("Conscript", "STATUS", "What's the status?", "litenetwork/vo/conscript/hg_check01.wav")
Schema.voices.Add("Conscript", "SEE ANYTHING", "Anyone see anything?", "litenetwork/vo/conscript/hg_check02.wav")
Schema.voices.Add("Conscript", "SITREP", "Sitrep.", "litenetwork/vo/conscript/hg_check03.wav")
Schema.voices.Add("Conscript", "SITREP2", "Give me a sitrep.", "litenetwork/vo/conscript/hg_check04.wav")
Schema.voices.Add("Conscript", "WHERE WE AT", "Where we at, gents?", "litenetwork/vo/conscript/hg_check05.wav")
Schema.voices.Add("Conscript", "HOW WE DOING", "How we doing?", "litenetwork/vo/conscript/hg_check06.wav")
Schema.voices.Add("Conscript", "WHATS GOING ON", "What's going on?", "litenetwork/vo/conscript/hg_check07.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD TO GO", "Are we good to go?", "litenetwork/vo/conscript/hg_check08.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD TO GO2", "Are we good to go?", "litenetwork/vo/conscript/hg_check08_var01.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD TO GO3", "Good to go?", "litenetwork/vo/conscript/hg_check09.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD TO GO4", "Good to go?", "litenetwork/vo/conscript/hg_check09_var01.wav")
Schema.voices.Add("Conscript", "CHECK SECTORS", "Check your sectors.", "litenetwork/vo/conscript/hg_check10.wav")
Schema.voices.Add("Conscript", "CHECK SECTORS", "Check those sectors.", "litenetwork/vo/conscript/hg_check10_var01.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD", "Are we good?", "litenetwork/vo/conscript/hg_check11.wav")
Schema.voices.Add("Conscript", "ARE WE GOOD2", "Are we good?", "litenetwork/vo/conscript/hg_check11_var01.wav")
Schema.voices.Add("Conscript", "WE GOOD", "We good?", "litenetwork/vo/conscript/hg_check12_subd01.wav")

-- clear

Schema.voices.Add("Conscript", "AREA CLEAR", "Area clear.", "litenetwork/vo/conscript/hg_clear01.wav")
Schema.voices.Add("Conscript", "ALL CLEAR", "All clear.", "litenetwork/vo/conscript/hg_clear02.wav")
Schema.voices.Add("Conscript", "NO THREATS", "No threats over here.", "litenetwork/vo/conscript/hg_clear04_extrm01.wav")
Schema.voices.Add("Conscript", "ALL THREATS DEAD", "All threats are dead.", "litenetwork/vo/conscript/hg_clear06.wav")
Schema.voices.Add("Conscript", "AREA CLEAR2", "Area is clear.", "litenetwork/vo/conscript/hg_clear07.wav")
Schema.voices.Add("Conscript", "ALL CLEAR2", "All clear, no threats.", "litenetwork/vo/conscript/hg_clear08.wav")
Schema.voices.Add("Conscript", "NO THREATS2", "I see no threats.", "litenetwork/vo/conscript/hg_clear09.wav")
Schema.voices.Add("Conscript", "NO TARGETS", "I see no targets.", "litenetwork/vo/conscript/hg_clear10.wav")
Schema.voices.Add("Conscript", "THATS ALL OF THEM", "That's all of them.", "litenetwork/vo/conscript/hg_clear12.wav")
Schema.voices.Add("Conscript", "AREA SECURE", "Area secure.", "litenetwork/vo/conscript/hg_clear13.wav")
Schema.voices.Add("Conscript", "THEYRE DEAD", "They're dead.", "litenetwork/vo/conscript/hg_clear14.wav")
Schema.voices.Add("Conscript", "WERE GOOD", "We're good.", "litenetwork/vo/conscript/hg_clear15.wav")

-- cover

Schema.voices.Add("Conscript", "COVER", "Take cover!", "litenetwork/vo/conscript/hg_cover01.wav")
Schema.voices.Add("Conscript", "GET AWAY", "Get away from them!", "litenetwork/vo/conscript/hg_cover02.wav")
Schema.voices.Add("Conscript", "GET AWAY2", "Get away from them!", "litenetwork/vo/conscript/hg_cover02_var01.wav")
Schema.voices.Add("Conscript", "COVER2", "Find cover!", "litenetwork/vo/conscript/hg_cover03.wav")
Schema.voices.Add("Conscript", "RUN", "Run!", "litenetwork/vo/conscript/hg_cover04.wav")
Schema.voices.Add("Conscript", "RUN2", "Run, run!", "litenetwork/vo/conscript/hg_cover04_var01.wav")
Schema.voices.Add("Conscript", "GET BACK", "Get back! Get back!", "litenetwork/vo/conscript/hg_cover06.wav")
Schema.voices.Add("Conscript", "HOLT SHIT", "Holy shit!", "litenetwork/vo/conscript/hg_cover07.wav")
Schema.voices.Add("Conscript", "HOLY SHIT2", "Holy shit!", "litenetwork/vo/conscript/hg_cover07_subd01.wav")
Schema.voices.Add("Conscript", "HOLY SHIT3", "Holy shit!", "litenetwork/vo/conscript/hg_cover07_var01.wav")
Schema.voices.Add("Conscript", "WITHDRAW", "Withdraw!", "litenetwork/vo/conscript/hg_cover08.wav")
Schema.voices.Add("Conscript", "COVER3", "Find some cover!", "litenetwork/vo/conscript/hg_cover10.wav")
Schema.voices.Add("Conscript", "JESUS", "Jesus!", "litenetwork/vo/conscript/hg_cover11.wav")
Schema.voices.Add("Conscript", "MOVE AWAY", "Move! Move away!", "litenetwork/vo/conscript/hg_cover12.wav")
Schema.voices.Add("Conscript", "GOD DAMN", "God damn!", "litenetwork/vo/conscript/hg_cover13.wav")
Schema.voices.Add("Conscript", "FALL BACK", "Fall back!", "litenetwork/vo/conscript/hg_cover14.wav")
Schema.voices.Add("Conscript", "FALL BACK2", "Fall back!", "litenetwork/vo/conscript/hg_cover14_var02.wav")
Schema.voices.Add("Conscript", "HOLD POSITION", "Hold this position!", "litenetwork/vo/conscript/hg_cover15.wav")
Schema.voices.Add("Conscript", "PEEL BACK", "Peel back!", "litenetwork/vo/conscript/hg_cover16.wav")
Schema.voices.Add("Conscript", "PEEL BACK2", "Peel back! Peel back!", "litenetwork/vo/conscript/hg_cover16_var01.wav")
Schema.voices.Add("Conscript", "PEEL", "Peel!", "litenetwork/vo/conscript/hg_cover17.wav")
Schema.voices.Add("Conscript", "PEEL2", "Peel, peel!", "litenetwork/vo/conscript/hg_cover17_var01.wav")

-- grenade

Schema.voices.Add("Conscript", "GRENADE", "Grenade!", "litenetwork/vo/conscript/hg_gren01.wav")
Schema.voices.Add("Conscript", "GRENADE2", "Grenade!", "litenetwork/vo/conscript/hg_gren02.wav")
Schema.voices.Add("Conscript", "GRENADE3", "Grenade!", "litenetwork/vo/conscript/hg_gren03.wav")
Schema.voices.Add("Conscript", "GRENADE4", "Grenade!", "litenetwork/vo/conscript/hg_gren04.wav")
Schema.voices.Add("Conscript", "GRENADE5", "That's a grenade!", "litenetwork/vo/conscript/hg_gren05.wav")
Schema.voices.Add("Conscript", "GRENADE6", "That's a grenade!", "litenetwork/vo/conscript/hg_gren05_var01.wav")
Schema.voices.Add("Conscript", "BACK BACK", "Back, back!", "litenetwork/vo/conscript/hg_gren06.wav")
Schema.voices.Add("Conscript", "JESUS2", "Jesus!", "litenetwork/vo/conscript/hg_gren07.wav")
Schema.voices.Add("Conscript", "JESUS3", "Jesus!", "litenetwork/vo/conscript/hg_gren07_var01.wav")
Schema.voices.Add("Conscript", "JESUS4", "Agh, Jesus!", "litenetwork/vo/conscript/hg_gren07_var03.wav")
Schema.voices.Add("Conscript", "JESUS5", "Ah, Jesus!", "litenetwork/vo/conscript/hg_gren07_var04.wav")
Schema.voices.Add("Conscript", "SHIT SHIT SHIT", "Shit, shit shit!", "litenetwork/vo/conscript/hg_gren08.wav")
Schema.voices.Add("Conscript", "GET BACK2", "Get back! Get back!", "litenetwork/vo/conscript/hg_gren09.wav")
Schema.voices.Add("Conscript", "OH SHIT", "Oh shit!", "litenetwork/vo/conscript/hg_gren10.wav")
Schema.voices.Add("Conscript", "OH SHIT2", "Oh shit!", "litenetwork/vo/conscript/hg_gren10_var01.wav")
Schema.voices.Add("Conscript", "OH SHIT3", "Oh shit!", "litenetwork/vo/conscript/hg_gren10_var03.wav")
Schema.voices.Add("Conscript", "OH SHIT4", "Oh shit!", "litenetwork/vo/conscript/hg_gren11.wav")
Schema.voices.Add("Conscript", "AGH", "Agh!", "litenetwork/vo/conscript/hg_gren12.wav")
Schema.voices.Add("Conscript", "AGH2", "Agh!", "litenetwork/vo/conscript/hg_gren13.wav")
Schema.voices.Add("Conscript", "AGH3", "Agh!", "litenetwork/vo/conscript/hg_gren13_var02.wav")

-- hit

Schema.voices.Add("Conscript", "IM HIT", "I'm hit!", "litenetwork/vo/conscript/hg_hit01.wav")
Schema.voices.Add("Conscript", "IM HIT2", "I'm hit!", "litenetwork/vo/conscript/hg_hit02.wav")

-- idle

Schema.voices.Add("Conscript", "DOGS BARKING", "My dogs are barking.", "litenetwork/vo/conscript/hg_idle01.wav")
Schema.voices.Add("Conscript", "SICK OF FIREWATCH", "I'm sick of firewatch.", "litenetwork/vo/conscript/hg_idle02.wav")
Schema.voices.Add("Conscript", "GETTING RELIEVED", "When are we getting relieved?", "litenetwork/vo/conscript/hg_idle03.wav")
Schema.voices.Add("Conscript", "UGH", "Ugh.", "litenetwork/vo/conscript/hg_idle04.wav")
Schema.voices.Add("Conscript", "MESSED UP", "This is messed up man.", "litenetwork/vo/conscript/hg_idle07.wav")
Schema.voices.Add("Conscript", "GOTTA PISS", "Shit, I gotta piss.", "litenetwork/vo/conscript/hg_idle09.wav")
Schema.voices.Add("Conscript", "IM HUNGRY", "Man I'm hungry. When do we eat?", "litenetwork/vo/conscript/hg_idle12.wav")
Schema.voices.Add("Conscript", "MORE GUYS", "I feel like we need more guys here.", "litenetwork/vo/conscript/hg_idle13.wav")

-- medic

Schema.voices.Add("Conscript", "IM HURT GUYS", "I'm hurt guys!", "litenetwork/vo/conscript/hg_medic04.wav")
Schema.voices.Add("Conscript", "SOMEBODY HELP", "Somebody, help me!", "litenetwork/vo/conscript/hg_medic05.wav")
Schema.voices.Add("Conscript", "HELP", "Help!", "litenetwork/vo/conscript/hg_medic06.wav")

-- monster

Schema.voices.Add("Conscript", "JESUS CHRIST", "Jesus Christ!", "litenetwork/vo/conscript/hg_monst01.wav")
Schema.voices.Add("Conscript", "OH MY GOD", "Oh my God!", "litenetwork/vo/conscript/hg_monst02.wav")
Schema.voices.Add("Conscript", "XRAY", "X-Ray!", "litenetwork/vo/conscript/hg_monst06.wav")
Schema.voices.Add("Conscript", "XRAY SPOTTED", "X-Ray spotted!", "litenetwork/vo/conscript/hg_monst03.wav")
Schema.voices.Add("Conscript", "XRAY SPOTTED2", "X-Ray spotted!", "litenetwork/vo/conscript/hg_monst03_var01.wav")
Schema.voices.Add("Conscript", "HOLY SHIT4", "Holy shit!", "litenetwork/vo/conscript/hg_monst04.wav")
Schema.voices.Add("Conscript", "WHAT THE HELL", "What the hell?!", "litenetwork/vo/conscript/hg_monst05.wav")
Schema.voices.Add("Conscript", "WHAT THE HELL2", "Oh, what the hell?!", "litenetwork/vo/conscript/hg_monst05_var01.wav")
Schema.voices.Add("Conscript", "XRAY2", "X-Ray! X-Ray!", "litenetwork/vo/conscript/hg_monst06_var01.wav")
Schema.voices.Add("Conscript", "XRAY CONTACT", "X-Ray contact!", "litenetwork/vo/conscript/hg_monst07.wav")
Schema.voices.Add("Conscript", "CONTACT10", "Contact!", "litenetwork/vo/conscript/hg_monst08.wav")
Schema.voices.Add("Conscript", "CONTACT11", "Contact!", "litenetwork/vo/conscript/hg_monst09.wav")
Schema.voices.Add("Conscript", "CONTACT12", "Contact! Contact!", "litenetwork/vo/conscript/hg_monst11.wav")
Schema.voices.Add("Conscript", "LOOK OUT", "Look out!", "litenetwork/vo/conscript/hg_monst13.wav")
Schema.voices.Add("Conscript", "LOOK OUT2", "Look out!", "litenetwork/vo/conscript/hg_monst13_var01.wav")
Schema.voices.Add("Conscript", "LOOK OUT3", "Shit, look out!", "litenetwork/vo/conscript/hg_monst12.wav")
Schema.voices.Add("Conscript", "LOOK OUT4", "Shit, look out!", "litenetwork/vo/conscript/hg_monst12_var01.wav")
Schema.voices.Add("Conscript", "UGLIES", "We've got uglies!", "litenetwork/vo/conscript/hg_monst14.wav")
Schema.voices.Add("Conscript", "UGLIES2", "We've got uglies!", "litenetwork/vo/conscript/hg_monst14_var01.wav")
Schema.voices.Add("Conscript", "UGLIES3", "We've got uglies!", "litenetwork/vo/conscript/hg_monst14_var02.wav")
Schema.voices.Add("Conscript", "INCOMING", "Incoming!", "litenetwork/vo/conscript/hg_monst15.wav")
Schema.voices.Add("Conscript", "INCOMING2", "Incoming!", "litenetwork/vo/conscript/hg_monst15_extrm01.wav")
Schema.voices.Add("Conscript", "XRAYS", "X-Rays!", "litenetwork/vo/conscript/hg_monst16.wav")
Schema.voices.Add("Conscript", "XRAYS2", "X-Rays!", "litenetwork/vo/conscript/hg_monst16_var01.wav")
Schema.voices.Add("Conscript", "XRAYS3", "Incoming X-Rays!", "litenetwork/vo/conscript/hg_monst17.wav")
Schema.voices.Add("Conscript", "ALIEN", "Alien!", "litenetwork/vo/conscript/hg_monst18.wav")
Schema.voices.Add("Conscript", "UGLIES4", "Uglies, incoming!", "litenetwork/vo/conscript/hg_monst19.wav")
Schema.voices.Add("Conscript", "UGLIES5", "Uglies!", "litenetwork/vo/conscript/hg_monst20.wav")

-- question

Schema.voices.Add("Conscript", "STAY ALERT", "Stay alert, gentlemen.", "litenetwork/vo/conscript/hg_question01.wav")
Schema.voices.Add("Conscript", "EYES PEELED", "Keep your eyes peeled, guys.", "litenetwork/vo/conscript/hg_question02.wav")
Schema.voices.Add("Conscript", "EYES PEELED2", "Keep your eyes peeled, guys.", "litenetwork/vo/conscript/hg_question02_extrm01.wav")
Schema.voices.Add("Conscript", "EYES PEELED3", "Keep your eyes peeled, guys.", "litenetwork/vo/conscript/hg_question02_var01.wav")
Schema.voices.Add("Conscript", "YOU GUYS GOOD", "You guys good?", "litenetwork/vo/conscript/hg_question03.wav")
Schema.voices.Add("Conscript", "EVERYONE OK", "Everyone ok?", "litenetwork/vo/conscript/hg_question04.wav")
Schema.voices.Add("Conscript", "EYES OPEN", "Eyes open.", "litenetwork/vo/conscript/hg_question05.wav")
Schema.voices.Add("Conscript", "EYES PEELED4", "Eyes peeled, gents.", "litenetwork/vo/conscript/hg_question06.wav")
Schema.voices.Add("Conscript", "STAY ALERT2", "Stay alert.", "litenetwork/vo/conscript/hg_question07.wav")
Schema.voices.Add("Conscript", "STAY ALERT3", "Stay alert, guys.", "litenetwork/vo/conscript/hg_question08.wav")
Schema.voices.Add("Conscript", "SWIVEL", "Keep your head on a swivel.", "litenetwork/vo/conscript/hg_question09.wav")
Schema.voices.Add("Conscript", "EVERYONE GOOD", "Everyone good?", "litenetwork/vo/conscript/hg_question10.wav")
Schema.voices.Add("Conscript", "DONT SEE ANYTHING", "I don't see anything.", "litenetwork/vo/conscript/hg_question11.wav")
Schema.voices.Add("Conscript", "NOTHING HERE", "There's nothing here.", "litenetwork/vo/conscript/hg_question12.wav")
Schema.voices.Add("Conscript", "NOTHING HERE2", "There's nothing here.", "litenetwork/vo/conscript/hg_question12_var01.wav")
Schema.voices.Add("Conscript", "GOT NOTHING", "I got nothing.", "litenetwork/vo/conscript/hg_question13.wav")

-- taunt

Schema.voices.Add("Conscript", "SOMETHING FOR YOU", "I got something for you!", "litenetwork/vo/conscript/hg_taunt06.wav")
Schema.voices.Add("Conscript", "SOMETHING FOR YOU2", "I got something for you!", "litenetwork/vo/conscript/hg_taunt06_var01.wav")
Schema.voices.Add("Conscript", "SOMETHING FOR YOU3", "I got something for you!", "litenetwork/vo/conscript/hg_taunt06_var02.wav")
Schema.voices.Add("Conscript", "SOMETHING FOR YOU4", "I got something for you!", "litenetwork/vo/conscript/hg_taunt06_var03.wav")
Schema.voices.Add("Conscript", "YOU GOT NOTHING", "You got nothing!", "litenetwork/vo/conscript/hg_taunt09.wav")
Schema.voices.Add("Conscript", "YOU GOT NOTHING2", "You got nothing!", "litenetwork/vo/conscript/hg_taunt09_var01.wav")
Schema.voices.Add("Conscript", "YOU GOT NOTHING3", "You got nothing!", "litenetwork/vo/conscript/hg_taunt09_var02.wav")
Schema.voices.Add("Conscript", "YOU GOT NOTHING4", "You got nothing! Nothing!", "litenetwork/vo/conscript/hg_taunt09_var03.wav")
Schema.voices.Add("Conscript", "ALL YOU GOT", "Is that all you got?!", "litenetwork/vo/conscript/hg_taunt10.wav")
Schema.voices.Add("Conscript", "ALL YOU GOT2", "Is that all you got?!", "litenetwork/vo/conscript/hg_taunt10_var01.wav")
Schema.voices.Add("Conscript", "ALL YOU GOT3", "Is that all you got?!", "litenetwork/vo/conscript/hg_taunt10_var02.wav")
Schema.voices.Add("Conscript", "KICK YOUR ASS", "We're gonna kick your ass!", "litenetwork/vo/conscript/hg_taunt_special01.wav")
Schema.voices.Add("Conscript", "KICK YOUR ASS2", "We're gonna kick your ass!", "litenetwork/vo/conscript/hg_taunt_special01_var01.wav")
Schema.voices.Add("Conscript", "KILL THAT BITCH", "Kill that son of a bitch!", "litenetwork/vo/conscript/hg_taunt_special03.wav")

-- throw

Schema.voices.Add("Conscript", "FIRE IN THE HOLE", "Fire in the hole!", "litenetwork/vo/conscript/hg_throw01.wav")
Schema.voices.Add("Conscript", "THROWING GRENADE", "I'm throwing a grenade!", "litenetwork/vo/conscript/hg_throw02.wav")
Schema.voices.Add("Conscript", "THROWING A FRAG", "I'm throwing a frag!", "litenetwork/vo/conscript/hg_throw02_var01.wav")
Schema.voices.Add("Conscript", "FRAG GOING OUT", "Frag going out!", "litenetwork/vo/conscript/hg_throw03.wav")
Schema.voices.Add("Conscript", "FRAG OUT", "Frag out!", "litenetwork/vo/conscript/hg_throw04.wav")
Schema.voices.Add("Conscript", "EVERYBODY DOWN", "Everybody down!", "litenetwork/vo/conscript/hg_throw05.wav")
Schema.voices.Add("Conscript", "EVERYBODY DOWN2", "Everybody get down!", "litenetwork/vo/conscript/hg_throw05_var01.wav")
Schema.voices.Add("Conscript", "FRAG OUT2", "Watch out guys, frag out!", "litenetwork/vo/conscript/hg_throw06.wav")

Schema.voices.AddClass("Conscript", function(ply)
    return ( ply:Team() == FACTION_CONSCRIPT )
end)
